version: '3.9'

networks:
  atdnetwork:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-service
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/error.log:/var/log/nginx/error.log
      - ./nginx/log/access.log:/var/log/nginx/access.log
    depends_on:
      - php
#      - mysql
    networks:
      - atdnetwork

#  mysql:
#    image: mysql:5.7.32
#    container_name: mysql-service
#    restart: on-failure
#    tty: true
#    ports:
#      - "4306:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
#    environment:
#      MYSQL_DATABASE: webapp
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password1
#      MYSQL_ROOT_PASSWORD: password1
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    networks:
#      - atdnetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-service
    volumes:
      - ./:/var/www/html
    ports:
      - "9011:9000"
    networks:
      - atdnetwork
